<h2 id="Contents">Contents<a href="#Contents"></a></h2>
        <ol>
        <li><a class="" href="#Imports">Imports</a></li>
<li><a class="" href="#Eigenvalue-Problem">Eigenvalue Problem</a></li>
<ol><li><a class="" href="#Solving-It-Algebraically">Solving It Algebraically</a></li>
<ol><li><a class="" href="#Eigenvalues">Eigenvalues</a></li>
</ol><li><a class="" href="#Iterative-Method-To-Get-The-Largest-Eigenvalue">Iterative Method To Get The Largest Eigenvalue</a></li>
</ol>

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import sympy as sp

# Eigenvalue Problem

Let $\mathbf{A}$ be a square matrix of size $n \times n$. The eigenvalue problem is to find the eigenvalues and eigenvectors of $\mathbf{A}$ defined as:
$$
\mathbf{A} \mathbf{v} = \lambda \mathbf{v}
$$
Here, $\mathbf{v}$ is the eigenvector and $\lambda$ is the eigenvalue.

## Solving It Algebraically

The problem, $\mathbf{A} \mathbf{v} = \lambda \mathbf{v}$ cab be written as $(\mathbf{A} -  \lambda I) \mathbf{v} = \mathbf{0}$. Taking the determinant of the matrix, we get:
$$
\det(\mathbf{A} - \lambda I) = 0
$$
This is called the characteristic equation. Solving this gives the eigenvalue of $\mathbf{A}$. The eignevectors are then calculated using the known values of the eigenvalue.

### Eigenvalues

In [16]:
def calc_eigenvalue(A):
    """
    Calculate the eigenvalue of a matrix A.
    """
    #Check for square matrix
    if A.shape[0] != A.shape[1]:
        raise ValueError("A is not a square matrix")

    #Check for Invertible Matrix
    if np.linalg.det(A) == 0:
        raise ValueError("A is not invertible")
    #Define the identity matrix
    A = sp.Matrix(A)
    I = sp.Identity(A.shape[0])
    #The caharacteristic eqauation
    x = sp.Symbol('x')
    C = (A-x*I)
    equation = sp.Eq(C,0)
    #Solve the equation
    eigenvalue = sp.solve(equation, x)
    #Return the eigenvalue
    return eigenvalue

In [20]:
calc_eigenvalue(B)

array([1, 2, 3])

In [21]:
calc_eigenvalue(C)

array('Hello', dtype='<U5')

## Iterative Method To Get The Largest Eigenvalue

In [44]:
def largest_eig(A, tol=1e-6, max_iter=100):
    if A.shape[0] != A.shape[1]:
        raise ValueError("A is not a square matrix")
    
    if np.linalg.det(A) == 0:
        raise ValueError("A is not invertible")
        
    x0 = np.ones((A.shape[0], 1))
    lambd0 = 1
    iter = 0
    while True:
        iter+=1
        if iter > max_iter:
            print(f"{max_iter} Iteractions Done! Not converged")
            break
        Ax = np.dot(A, x0)
        lambd_next = Ax.max()
        x_next = Ax/lambd_next
        if np.abs(lambd_next - lambd0) < tol:
            break
        x0 = x_next
        lambd0 = lambd_next
    return lambd_next, x_next

In [45]:
A = np.array([[5, 7], [3, 2]])
A.shape
largest_eig(A)

(8.321825407715025,
 array([[1.        ],
        [0.47454648]]))

In [28]:
B = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
largest_eig(B)

(12.928203193763359,
 array([[0.3660254],
        [0.6830127],
        [1.       ]]))

In [29]:
np.linalg.eig(B)

(array([ 1.29282032e+01, -9.28203230e-01,  9.10085294e-16]),
 array([[-0.28932501, -0.80222426,  0.40824829],
        [-0.53988782, -0.10747767, -0.81649658],
        [-0.79045062,  0.58726892,  0.40824829]]))